package com.umair.app.doordash.model

import com.google.gson.annotations.SerializedName

data class Restaurant(
        @SerializedName("phone_number") val phoneNumber: String = "",
        @SerializedName("yelp_review_count") val yelpReviewCount: Int = 0,
        @SerializedName("is_consumer_subscription_eligible") val isConsumerSubscriptionEligible: Boolean = false,
        @SerializedName("offers_delivery") val offersDelivery: Boolean = false,
        @SerializedName("max_order_size") val maxOrderSize: Int?,
        @SerializedName("delivery_fee") val deliveryFee: Int = 0,
        @SerializedName("max_composite_score") val maxCompositeScore: Int = 0,
        @SerializedName("id") val id: Int = 0,
        @SerializedName("average_rating") val averageRating: Double = 0.0,
        @SerializedName("tags") val tags: List<String> = listOf(),
        @SerializedName("delivery_radius") val deliveryRadius: Int = 0,
        @SerializedName("inflation_rate") val inflationRate: Double = 0.0,
        @SerializedName("menus") val menus: List<Menu> = listOf(),
        @SerializedName("show_store_menu_header_photo") val showStoreMenuHeaderPhoto: Boolean = false,
        @SerializedName("composite_score") val compositeScore: Int = 0,
        @SerializedName("offers_pickup") val offersPickup: Boolean = false,
        @SerializedName("number_of_ratings") val numberOfRatings: Int = 0,
        @SerializedName("status_type") val statusType: String = "",
        @SerializedName("is_only_catering") val isOnlyCatering: Boolean = false,
        @SerializedName("status") val status: String = "",
        @SerializedName("delivery_fee_details") val deliveryFeeDetails: DeliveryFeeDetails = DeliveryFeeDetails(),
        @SerializedName("object_type") val objectType: String = "",
        @SerializedName("description") val description: String = "",
        @SerializedName("business") val business: Business = Business(),
        @SerializedName("yelp_biz_id") val yelpBizId: String = "",
        @SerializedName("asap_time") val asapTime: Int?,
        @SerializedName("yelp_rating") val yelpRating: Double = 0.0,
        @SerializedName("extra_sos_delivery_fee") val extraSosDeliveryFee: Int = 0,
        @SerializedName("business_id") val businessId: Int = 0,
        @SerializedName("special_instructions_max_length") val specialInstructionsMaxLength: Boolean = false,
        @SerializedName("cover_img_url") val coverImgUrl: String = "",
        @SerializedName("address") val address: Address = Address(),
        @SerializedName("price_range") val priceRange: Int = 0,
        @SerializedName("slug") val slug: String = "",
        @SerializedName("show_suggested_items") val showSuggestedItems: Boolean = false,
        @SerializedName("name") val name: String = "",
        @SerializedName("is_newly_added") val isNewlyAdded: Boolean = false,
        @SerializedName("is_good_for_group_orders") val isGoodForGroupOrders: Boolean = false,
        @SerializedName("service_rate") val serviceRate: Double = 0.0,
        @SerializedName("merchant_promotions") val merchantPromotions: List<MerchantPromotion> = listOf(),
        @SerializedName("header_image_url") val headerImageUrl: String = ""
)